apiVersion: v1
kind: Service
metadata:
  name: twitter-middleware
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: twitter-middleware
