# Either modify the following file and add your secrets or use the shell script in the parent folder to interactively add credentials
apiVersion: v1
kind: Secret
metadata:
  name: twitter-backend-secret
type: Opaque
data:
  CONNECTION_URI: {{ MongoDB.Cluster.URI }}
  SLACK_WEBHOOK_URI: {{ Slack.Webhook.URI }}
  JWT_Secret: {{ App.Secrets.JWT }}
  AWS_ACCESS_KEY_ID: {{ AWS.Access.Key.Id }}
  AWS_SECRET_ACCESS_KEY: {{ AWS.Secret.Access.Key }}