# Either modify the following file and add your secrets or use the shell script in the parent folder to interactively add credentials
apiVersion: v1
kind: Secret
metadata:
  name: twitter-middleware-secret
type: Opaque
data:
  SLACK_WEBHOOK_URI: {{ Slack.Webhook.URI }}
  RAPID_API_KEY: {{ Rapid.Api.Key }}