apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitter-middleware
  labels:
    app: twitter-middleware
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twitter-middleware
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: twitter-middleware
    spec:
      containers:
        - name: twitter-middleware
          image: rishijatania/twitter-middleware
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: twitter-middleware-config
            - secretRef:
                name: twitter-middleware-secret
          ports:
            - containerPort: 5000