apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitter-queue
  labels:
    app: twitter-queue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twitter-queue
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: twitter-queue
    spec:
      containers:
        - name: redis
          image: redislabs/rejson:latest
          ports:
            - containerPort: 6379